confirmonquit: false
git:
  autofetch: true
  merging:
    manualcommit: false
  skiphookprefix: WIP
  paging:
    colorArg: always
    pager: delta --paging=never --24-bit-color=never
gui:
  commitlength:
    show: true
  mouseevents: false
  scrollheight: 2
  scrollpastbottom: true
  theme:
    lightTheme: false
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - blue
reporting: "off"
splashupdatesindex: 0
startuppopupversion: 1
keybinding:
  universal:
    goInto: 'l'
    confirm: 'l'
    quit: '<esc>'
    return: 'h' # return to previous menu, will quit if there's nowhere to return
